services:
  backend:
    build: .
    container_name: fast-dlp
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: [ "./entrypoint.sh" ]
